### ISSUE TITLE
pretrained resources?

### ISSUE THREAD

**Issue by romanovzky** [CyberZHG/keras-bi-lm#1]
Hi there,

I found your repo as I'm starting to tinker with bi-LM for an assortment of NLP tasks I want to improve.

I really like your code and I'll be using your package, but due to time constraints for my initial probatory assessment, I'd like to try it with a pre-trained bi-LM file, any idea where I could find one?  What specifications would it need to have?

Cheers!

**Comment by CyberZHG** [comment]
Sorry for the late reply since I turned off the notifications accidentally.

I only trained the model for simplified Chinese characters with Wikipedia, therefore there is no pre-trained model for English words yet.

**Comment by romanovzky** [comment]
Thanks for the reply! I've been tinkering with it and making my own models from different corpora now :)
